apiVersion: v1
kind: Service
metadata:
  name: ml-svc
  labels:
    name: ml-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    name: ml-microservice-kubernetes
    version: "1.0"
  type: LoadBalancer
